import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { Navbar } from '../components/Navbar'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>GManriqe | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar></Navbar>

            <main className={styles.main}>
                <h2>Home Page</h2>
                <h1 className={styles.title}>
                    {/* Ir a <a href="/about">About</a> */}
                    Ir a <Link href="/about">About</Link>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>
            </main>


        </div>
    )
}
